### ISSUE TITLE
Page not being included

### ISSUE THREAD

**Issue by Stono** [Fried-Chicken/ghost-static-site-generator#7]
Hey, 
I use formspree for "contact me" https://karlstoney.com/contact - which upon success redirects back to https://karlstoney.com/thanks.

`/thanks` exists in ghost as a `page` but it isn't being included in my static site content.

You can see it in my sitemap here: https://karlstoney.com/sitemap-pages.xml

Not sure what's going wrong, any ideas?

**Comment by Fried-Chicken** [comment]
Hey @Stono 

I've thought about this before briefly. So it's not included because there are no links to this page on the site anywhere. I did think of adding a flag before, but then it's just too many flags. I'm thinking I could add a `.gssgconfig` where you can add all the settings and just run `gssg` instead.

What do you think?

**Comment by Stono** [comment]
Sounds like a great idea in general, but for this specific issue couldn't
you also traverse the sitemap.xml to ensure you're indexing all pages?

**Comment by Fried-Chicken** [comment]
That's a good idea, I think traversing the sitemap's better. Let me have a go at that.

**Comment by Stono** [comment]
Confirmed this is fixed

**Comment by Fried-Chicken** [comment]
Awesome
